BlogFelipeWeb/Models/Blog/ListarPostsViewModel.cs
using BlogFelipe.DB.Classes;
using BlogFelipeWeb.Models.Detalhes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogFelipeWeb.Models.ContUsuario
{
    public class ListarPostsViewModel
    {
//  Registro por pagina = 10
        public List<DetalhesPostViewModel> Posts { get; set; }
        public int iPaginaAtual { get; set; }
        public int iTotalDePaginas { get; set; }
        public string sTag { get; set; }
        public List<string> sTags { get; set; }
        public string sPesquisa { get; set; }
    }
}

BlogFelipeWeb/Controllers/Administracao/AdministracaoController.cs
using BlogFelipe.DB;
using BlogFelipe.DB.Classes;
using BlogFelipeWeb.Models.Administracao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFelipeWeb.Controllers.Administracao
{
    [Authorize]
    public class AdministracaoController : Controller
    {
        //// GET: Administracao
        
        public ActionResult index()
        {
            return View();
        }

        public ActionResult CadastrarPost()
        {
            var viewModel = new CadastrarPostViewModel();
            viewModel.Autor = "Felipe Borges Tomaz";
            viewModel.DataPublicacao = DateTime.Now;
            viewModel.HoraPublicacao = DateTime.Now;
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult CadastrarPost(CadastrarPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new ConexaoBanco();
                var post = new Post();

                //DateTime dDataPublicacao = DateTime.Now.Date;
                //DateTime dHoraPublicacao = DateTime.Now;
                //DateTime dConcatenar = dDataPublicacao + dHoraPublicacao;
                var dDataPublicao = new DateTime(
                        viewModel.DataPublicacao.Year,
                        viewModel.DataPublicacao.Month,
                        viewModel.DataPublicacao.Day,
                        viewModel.HoraPublicacao.Hour,
                        viewModel.HoraPublicacao.Minute,
                        viewModel.HoraPublicacao.Second
                    );

                post.sAutor = viewModel.Autor;
                post.dDataPublicacao = dDataPublicao;
                post.sDescricao = viewModel.Descricao;
                post.sResumo = viewModel.Resumo;
                post.sTitulo = viewModel.Titulo;
                post.bVisivel = viewModel.Visivel;
                post.PostTags = new List<TagPost>();

                if(viewModel.Tags != null)
                {
                    foreach (var item in viewModel.Tags)
                    {
                        var tagExiste = (from p in conexao.Tags where p.sIDTag.ToLower() == item.ToLower() select p).Any();

                        if (!tagExiste)
                        {
                            var tagClass = new Tag();
                            tagClass.sIDTag = item;
                            conexao.Tags.Add(tagClass);
                        }

                        var postTag = new TagPost();
                        postTag.sIdTag = item;
                        post.PostTags.Add(postTag);
                    }
                }

                try { 

                conexao.Posts.Add(post);                
                conexao.SaveChanges();
                return RedirectToAction("Index");
                }
                catch (Exception exp)
                {
                    ModelState.AddModelError("Erro Banco:", exp.Message);
                }

            }
            return View(viewModel);
        }


        public ActionResult EditarPost(int id)
        {
            var viewModel = new CadastrarPostViewModel();
            var conexao = new ConexaoBanco();
            var post = conexao.Posts.Where(x => x.Id == id).FirstOrDefault();

            if (post == null)
            {
                throw new Exception(string.Format("Post com código {0} não encontrado.", id));
            }

            viewModel.Titulo = post.sTitulo;
            viewModel.Autor = post.sAutor;
            viewModel.DataPublicacao = post.dDataPublicacao;
            viewModel.HoraPublicacao = post.dDataPublicacao;
            viewModel.Visivel = post.bVisivel;
            viewModel.Descricao = post.sDescricao;
            viewModel.Resumo = post.sResumo;
            viewModel.id = post.Id;

            viewModel.Tags = (from p in post.PostTags select p.sIdTag).ToList();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditarPost(CadastrarPostViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new ConexaoBanco();
                var post = conexao.Posts.Where(x => x.Id == viewModel.id).FirstOrDefault();

                post.sTitulo = viewModel.Titulo;
                post.sAutor = viewModel.Autor;
                var DataPublicacao = new DateTime(
                    viewModel.DataPublicacao.Year,
                    viewModel.DataPublicacao.Month,
                    viewModel.DataPublicacao.Day,
                    viewModel.HoraPublicacao.Hour,
                    viewModel.HoraPublicacao.Minute,
                    viewModel.HoraPublicacao.Second
                    );
                post.dDataPublicacao = DataPublicacao;
                post.bVisivel = viewModel.Visivel;
                post.sDescricao = viewModel.Descricao;
                post.sResumo = viewModel.Resumo;
                var postsTagsAtuais = post.PostTags.ToList();

                foreach (var item in postsTagsAtuais)
                {
                    conexao.TagPosts.Remove(item);
                }

                if (viewModel.Tags != null)
                {
                    foreach (var item in viewModel.Tags)
                    {
                        var tagExiste = (from p in conexao.Tags where p.sIDTag.ToLower() == item.ToLower() select p).Any();

                        if (!tagExiste)
                        {
                            var tagClass = new Tag();
                            tagClass.sIDTag = item;
                            conexao.Tags.Add(tagClass);
                        }

                        var postTag = new TagPost();
                        postTag.sIdTag = item;
                        post.PostTags.Add(postTag);
                    }
                }

                try
                {
                    conexao.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception exp) {
                    ModelState.AddModelError("Erro Banco: ", exp.Message);
                }
            }
            return View(viewModel);
        }

        #region
        public ActionResult ExcluirPost(int id)
        {
            var conexao = new ConexaoBanco();
            var post = (from p in conexao.Posts where p.Id == id select p).FirstOrDefault();

            if (post == null)
            {
                throw new Exception(string.Format("Post código {0} não exite.", id));
            }
            conexao.Posts.Remove(post);
            conexao.SaveChanges();

            return RedirectToAction("Index", "Blog");
        }
        #endregion

        #region ExcluirComentario
        public ActionResult ExcluirComentario(int id)
        {
            var conexaoBanco = new ConexaoBanco();
            var comentario = (from p in conexaoBanco.Comentarios
                              where p.Id == id
                              select p).FirstOrDefault();
            if (comentario == null)
            {
                throw new Exception(string.Format("Comentário código {0} não foi encontrado.", id));
            }
            conexaoBanco.Comentarios.Remove(comentario);
            conexaoBanco.SaveChanges();

            var post = (from p in conexaoBanco.Posts
                        where p.Id == comentario.idPost
                        select p).First();
            return Redirect(Url.Action("Post", "Blog", new
            {
                ano = post.dDataPublicacao.Year,
                mes = post.dDataPublicacao.Month,
                dia = post.dDataPublicacao.Day,
                titulo = post.sTitulo,
                id = post.Id
            }) + "#comentarios");
        }
        #endregion
    }
}

BlogFelipeWeb/Controllers/Administracao/BlogController.cs
using BlogFelipe.DB;
using BlogFelipe.DB.Classes;
using BlogFelipeWeb.Models.Administracao;
using BlogFelipeWeb.Models.ContUsuario;
using BlogFelipeWeb.Models.Detalhes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFelipeWeb.Controllers.Administracao
{
    public class BlogController : Controller
    {
        // GET: Blog, string aceita nulo com padrão,
        public ActionResult Index(int? pagina, string tag, string pesquisa)
        {
            var conexao = new ConexaoBanco();

//  Se não for nulo
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registroPorPagina = 10;
            var posts = (from p in conexao.Posts where p.bVisivel select p);

//  Verificando se é nulo a tag
            if (!string.IsNullOrEmpty(tag))
            {
                //  Any acha o primiero valor, 
                posts = (from p in posts where p.PostTags.Any(x => x.sIdTag.ToUpper() == tag.ToUpper()) select p);
            }

//  Verifica quando não é nulo e nem vazio a pesquisa
            if (!string.IsNullOrEmpty(pesquisa))
            {
                posts = (from p in posts where p.sTitulo.ToUpper().Contains(pesquisa.ToUpper())
                        ||  p.sResumo.ToUpper().Contains(pesquisa.ToUpper())
                        ||  p.sDescricao.ToUpper().Contains(pesquisa.ToUpper())
                         select p);
            }

            var qtdeRegistros = posts.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdeRegistrosPular = (indiceDaPagina * registroPorPagina);
            //  Arendonta para cima
            var qtdePaginas = Math.Ceiling((decimal)qtdeRegistros / (decimal)registroPorPagina);

            var viewModel = new ListarPostsViewModel();
            viewModel.Posts = (from p in posts orderby p.dDataPublicacao descending select new DetalhesPostViewModel
            {
                DataPublicacao = p.dDataPublicacao,
                Autor = p.sAutor,
                Descricao = p.sDescricao,
                id = p.Id,
                Resumo = p.sResumo,
                Titulo = p.sTitulo,
                Visivel = p.bVisivel,
                QtdComentarios = p.Comentarios.Count
            }
            ).Skip(qtdeRegistrosPular).Take(registroPorPagina).ToList();


            viewModel.iPaginaAtual = paginaCorreta;
            viewModel.iTotalDePaginas = (int)qtdePaginas;
            viewModel.sTag = tag;

            viewModel.sTags = (from p in conexao.Tags where conexao.TagPosts.Any(x => x.sIdTag == p.sIDTag) orderby p.sIDTag ascending select p.sIDTag).ToList();

            viewModel.sPesquisa = pesquisa;
            return View(viewModel);
        }

        public ActionResult _Paginacao()
        {
            return PartialView();
        }

        #region
        public ActionResult Post(int id, int? pagina)
        {
            var conexao = new ConexaoBanco();
            var viewModel = new DetalhesPostViewModel();
            var post = (from p in conexao.Posts where p.Id == id select p).FirstOrDefault();

            if (post == null)
            {
                throw new Exception(string.Format("Post Código {0} não encontrado"));
            }
            preencherViewModel(viewModel, post, pagina);


            viewModel.Tags = (from p in post.PostTags select p.sIdTag).ToList();

            return View(viewModel);
        }

        private static void preencherViewModel(DetalhesPostViewModel viewModel, Post post, int? pagina)
        {
            viewModel.id = post.Id;
            viewModel.Titulo = post.sTitulo;
            viewModel.Autor = post.sAutor;
            viewModel.DataPublicacao = post.dDataPublicacao;
            viewModel.HoraPublicacao = post.dDataPublicacao;
            viewModel.Visivel = post.bVisivel;
            viewModel.Descricao = post.sDescricao;
            viewModel.Resumo = post.sResumo;
            viewModel.QtdComentarios = post.Comentarios.Count();
            viewModel.Descricao = post.sDescricao;
            //Adicionar tags
            viewModel.Tags = post.PostTags.Select(x => x.sIdTag).ToList();
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registroPorPagina = 10;
            var qtdeRegistros = post.Comentarios.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdeRegistrosPular = (indiceDaPagina * registroPorPagina);
            //  Arendonta para cima
            var qtdePaginas = Math.Ceiling((decimal)qtdeRegistros / (decimal)registroPorPagina);

            viewModel.iLComentarios = (from p in post.Comentarios orderby p.dDataHora descending select p)
            .Skip(qtdeRegistrosPular).Take(registroPorPagina).ToList();

            viewModel.iPaginaAtual = paginaCorreta;
            viewModel.iTotalPaginas = (int)qtdePaginas;
        }
        #endregion

        #region
        [HttpPost]
        public ActionResult Post(DetalhesPostViewModel viewModel)
        {
            var conexao = new ConexaoBanco();
            var post = (from p in conexao.Posts where p.Id == viewModel.id select p).FirstOrDefault();

            if (ModelState.IsValid)
            {

                if (post == null)
                {
                    throw new Exception(string.Format("Post código {0} não encontrado.", viewModel.id));
                }
                var comentario = new Comentario();
                comentario.bAdmPost = HttpContext.User.Identity.IsAuthenticated;
                comentario.lDescricao = viewModel.ComentarioDescricao;
                comentario.sEmail = viewModel.ComentarioEmail;
                comentario.idPost = viewModel.id;
                comentario.sNome = viewModel.ComentarioNome;
                comentario.sPaginaWeb = viewModel.ComentarioPaginaWeb;
                comentario.dDataHora = DateTime.Now;

                try
                {
                    conexao.Comentarios.Add(comentario);
                    conexao.SaveChanges();
                    return Redirect(Url.Action("Post", new
                    {
                        ano = post.dDataPublicacao.Year,
                        mes = post.dDataPublicacao.Month,
                        dia = post.dDataPublicacao.Day,
                        titulo = post.sTitulo,
                        id = post.Id
                    }) + "#comentarios");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            preencherViewModel(viewModel, post, null);
            return View(viewModel);
        }
        #endregion

        public ActionResult _PaginacaoPost()
        {
            return PartialView();
        }
    }
}

BlogFelipeWeb/Views/Blog/Index.cshtml
@model BlogFelipeWeb.Models.ContUsuario.ListarPostsViewModel

@{
    ViewBag.Title = "Posts";
    var tipoPesquisa = "";

    if (Model.sTag != null)
    {
        tipoPesquisa = string.Format("- tag: {0}", Model.sTag);
    }
}

@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Blog/Index.js")"></script>
}

<h2>Posts @tipoPesquisa</h2>
<div class="row">
    <div class="col-md-10">
        @foreach (var item in Model.Posts)
        {

        <h2>
                @Html.ActionLink(item.Titulo, "Post", "Blog", new
       {
           id = item.id,
           ano = item.DataPublicacao.Year,
           mes = item.DataPublicacao.Month,
           dia = item.DataPublicacao.Day,
           titulo = item.Titulo
       }, null)
        </h2>

        <div>
            <div class="icone-calendario div-imagem"></div>
            @item.DataPublicacao.ToString("dd/MM/yyyy HH:mm")
            <div class="icone-autor div-imagem"></div>
            @item.Autor
            <div class="icone-comentario div-imagem"> </div>
            @Html.ActionLink(item.QtdComentarios.ToString(), "Post", "Blog", new
               {
                   id = item.id,
                   ano = item.DataPublicacao.Year,
                   mes = item.DataPublicacao.Month,
                   dia = item.DataPublicacao.Day,
                   titulo = item.Titulo
               }, null)

            @if (Request.IsAuthenticated)
            {
                <div class="icone-editar div-imagem"></div>
                @Html.ActionLink("Editar", "EditarPost", "Administracao", new { id = item.id }, null)
                <div class="icone-excluir div-imagem "></div>
                @Html.ActionLink("Excluir", "ExcluirPost", "Administracao", new { id = item.id }, new { @class = "excluir-post" })
            }

        </div>

        <p><div>@item.Resumo</div></p>

        
            @Html.ActionLink("Continue Lendo!", "Post", "Blog", new
           {
               id = item.id,
               ano = item.DataPublicacao.Year,
               mes = item.DataPublicacao.Month,
               dia = item.DataPublicacao.Day,
               titulo = item.Titulo
           }, null)
        
        }

    </div>

    <div class="col-md-2">
    
        <h3> Tags </h3>

        <ul>
            @foreach(var item in Model.sTags)
            {
                <li>@Html.ActionLink(item, "Index","Blog", new { tag = item}, null)</li>
            }
        </ul>
    </div
>
</div>
        <p>@Html.Partial("_Paginacao", Model)</p>

BlogFelipeWeb/Views/Blog/Post.cshtml
@model BlogFelipeWeb.Models.Detalhes.DetalhesPostViewModel
@{
    ViewBag.Title = Model.Titulo;
}

@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Blog/Index.js")"></script>
}

@using (@Html.BeginForm())
{
    <div>
        <h1>@Model.Titulo</h1>
        <div>
            <div class="icone-calendario div-imagem"></div>
            @Model.DataPublicacao.ToString("dd/MM/yyy HH:mm")

            <div class="icone-autor div-imagem"></div>
            @Model.Autor.ToString()
            
            <div class="icone-comentario div-imagem"> </div>
            @Html.ActionLink(Model.QtdComentarios.ToString(), "Post", "Blog", new
                   {
                       id = Model.id,
                       ano = Model.DataPublicacao.Year,
                       mes = Model.DataPublicacao.Month,
                       dia = Model.DataPublicacao.Day,
                       titulo = Model.Titulo
                   }, null)

            @if (Request.IsAuthenticated)
            {
                        <div class="icone-excluir div-imagem "></div>
                        @Html.ActionLink("Excluir", "ExcluirPost", "Administracao", new { id = Model.id }, new { @class = "excluir-post" })
            }
        </div>

        @Model.Descricao 

        <h3>Tags</h3>
        <div class="form-group">
            <ul id="resultado">
                @if (Model.Tags != null)
                {
                    foreach (var item in Model.Tags)
                    {
                            <li>@Html.ActionLink(item, "Index", "Blog", new { tag = item }, null)</li>
                        //http://localhost:54578/Blog/Index?tag=Ronaldinho Coral
                        @*<li><span> @item</span><a tag="@item"></a></li>*@
                    }
                }
            </ul>
        </div>
    </div>

    <div>
        <h3>Novo Comentário</h3>
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary(true)
                @Html.HiddenFor(x => x.id)

                <div class="form-group">
                    @Html.LabelFor(m => m.ComentarioNome)
                    @Html.TextBoxFor(m => m.ComentarioNome, new { @class = "form-control"})
                    @Html.ValidationMessageFor(m => m.ComentarioNome)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ComentarioEmail)
                    @Html.TextBoxFor(m => m.ComentarioEmail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ComentarioEmail)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ComentarioPaginaWeb)
                    @Html.TextBoxFor(m => m.ComentarioPaginaWeb, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ComentarioPaginaWeb)
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ComentarioDescricao)
                    @Html.TextAreaFor(m => m.ComentarioDescricao, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ComentarioDescricao)
                </div>
                
                <p><input type="submit" value="Salvar" class="btn btn-primary"></p>
            }

        <div id="comentarios">
            <h3>Comentários</h3>
            @{
                var contador = 0;
            }
            @foreach (var item in Model.iLComentarios)
            {
                contador++;
                string id = "comentario" + contador.ToString();
                string cssClass = "text-info";
                if (item.bAdmPost)
                {
                    cssClass = "label label-info";
                }
                <div>
                    <a id="@item.Id"></a>
                    <p>
                        <span class="@cssClass">@item.sNome</span><br />
                        <small>
                            @item.dDataHora.ToString("dd/MM/yyyy HH:mm:ss")
                            @if (!string.IsNullOrEmpty(item.sPaginaWeb))
                            {
                                <text>|</text>
                                <a href="@item.sPaginaWeb">@item.sPaginaWeb</a>
                            }
                            @if (this.Request.IsAuthenticated)
                            {
                                <text>|</text>
                                @Html.ActionLink("Remover", "ExcluirComentario", "Administracao", new { id = item.Id }, new { @class = "excluir-comentario" })
                            }
                        </small>
                    </p>
                    @Html.Raw(Html.Encode(item.lDescricao).Replace("\n", "<br />"))
                </div>

                if (contador < this.Model.iLComentarios.Count)
                {
                    <hr />
                }
            }
        </div>
        @Html.Partial("_PaginacaoPost", Model)
    </div>
}

BlogFelipeWeb/Views/Blog/_Paginacao.cshtml
@model BlogFelipeWeb.Models.ContUsuario.ListarPostsViewModel

@if (Model.iTotalDePaginas > 1)
{
    var proximaPagina = Model.iPaginaAtual + 1;
    var paginaAnterior = Model.iPaginaAtual - 1;

    <div class="pagination">
        @if (Model.iPaginaAtual > 1)
        {
@*class= "classe-paginas*@
           <button> @Html.ActionLink("Pagina Anterior", "Index", "Blog", new { pagina = paginaAnterior, tag = Model.sTag, pesquisa = Model.sPesquisa }, new { rel = "prev" })</button>
            }
                    @if (Model.iPaginaAtual < Model.iTotalDePaginas)
                    {
           <button> @Html.ActionLink("Proxima Pagina", "Index", "Blog", new { pagina = proximaPagina, tag = Model.sTag, pesquisa = Model.sPesquisa }, new { rel = "prev" })</button>
            }
</div>
}

BlogFelipeWeb/Views/Blog/_PaginacaoPost.cshtml
@model BlogFelipeWeb.Models.Detalhes.DetalhesPostViewModel
@if (Model.iTotalPaginas > 1)
{
    var paginaAnterior = Model.iPaginaAtual - 1;
    var proximaPagina = Model.iPaginaAtual + 1;

    <div class="pagination">
        @if (Model.iPaginaAtual > 1)
        {
            <a href="@Url.Action("Post", new
                {
                    id = Model.id,
                    pagina = paginaAnterior
                })#comentarios" rel="prev">Página anterior</a>
            if (proximaPagina != -1)
            {
                <text>|</text>
            }
        }
        @if (proximaPagina != -1)
        {
            <a href="@Url.Action("Post", new
                {
                    id = Model.id,
                    pagina = proximaPagina
                })#comentarios" rel="prev">Próxima página</a>
        }
    </div>
}