BlogFelipeWeb/Models/Administracao/CadastrarPostViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlogFelipeWeb.Models.Administracao
{
    public class CadastrarPostViewModel
    {
        [DisplayName("ID")]
        [Required(ErrorMessage = "O campo ID é obrigatório.")]
        public int id { get; set; }

        [DisplayName("Título")]
        [Required(ErrorMessage ="O campo Título é obrigatório.")]
        [StringLength(100, MinimumLength = 2, 
        ErrorMessage = "A quantidade de caracteres no campo título deve ser entre {2} e {1}.")]
        public string Titulo { get; set; }

        [DisplayName("Autor")]
        [Required(ErrorMessage = "O campo Autor é obrigatório.")]
        [StringLength(100, MinimumLength = 2,
        ErrorMessage = "A quantidade de caracteres no campo Autor deve ser entre {2} e {1}.")]
        public string Autor { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "O campo Descrição é obrigatório.")]
        public string Descricao { get; set; }

        [DisplayName("Resumo")]
        [Required(ErrorMessage = "O campo Resumo é obrigatório.")]
        [StringLength(100, MinimumLength = 2,
        ErrorMessage = "A quantidade de caracteres no campo Resumo deve ser entre {2} e {1}.")]
        public string Resumo { get; set; }

        [DisplayName("Data de Publicação")]
        [Required(ErrorMessage = "O campo Data Publicação é obrigatório.")]
        public DateTime DataPublicacao { get; set; }

        [DisplayName("Hora de Publicação")]
        [Required(ErrorMessage = "O campo Hora de Publicação é obrigatório.")]
        public DateTime HoraPublicacao { get; set; }

        [DisplayName("Vísivel")]
        [Required(ErrorMessage = "O campo Vísivel é obrigatório.")]
        public bool Visivel { get; set; }

        public List<string> Tags { get; set; }
    }
}

BlogFelipeWeb/Models/Administracao/CadastrarUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BlogFelipeWeb.Models.Administracao
{
    public class CadastrarUsuarioViewModel
    {
        [DisplayName("ID Usuario")]
        [Required(ErrorMessage = "Campo Obrigatório")]        
        public int iId { get; set; }

        [DisplayName("Login")]
        [Required(ErrorMessage = "O campo Login é obrigatório.")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "A quantidade de caracteres no campo Login deve ser entre {2} e {1}.")]
        public string sLogin { get; set; }

        [DisplayName("Nome")]
        [Required(ErrorMessage = "O campo Nome é Obrigatório.")]
        [StringLength(100, MinimumLength = 4, ErrorMessage = "A quantidade de caracteres no campo Nome deve ser entre {2} e {1}")]
        public string sNome { get; set; }

        [DisplayName("Senha")]
        [Required(ErrorMessage = "O campo Senha é Obrigatório")]
        [StringLength(100, MinimumLength = 4, ErrorMessage = "A quantidade de caracteres no campo Senha deve ser entre {2} e {1}")]
        public string sSenha { get; set; }

        [DisplayName("Confirmar Senha")]
        [Required(ErrorMessage = "O campo Confirmar Senha é Obrigatório")]
        [StringLength(100, MinimumLength = 4, ErrorMessage = "A quantidade de caracteres no campo Senha deve ser entre {2} e {1}")]
        [Compare("sSenha", ErrorMessage = "As senhas digitadas não conferem.")]
        public string sConfirmarSenha { get; set; }
    }
}

BlogFelipeWeb/Controllers/Administracao/BlogController.cs
using BlogFelipe.DB;
using BlogFelipe.DB.Classes;
using BlogFelipeWeb.Models.Administracao;
using BlogFelipeWeb.Models.ContUsuario;
using BlogFelipeWeb.Models.Detalhes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFelipeWeb.Controllers.Administracao
{
    public class BlogController : Controller
    {
        // GET: Blog, string aceita nulo com padrão,
        public ActionResult Index(int? pagina, string tag, string pesquisa)
        {
            var conexao = new ConexaoBanco();

//  Se não for nulo
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registroPorPagina = 10;
            var posts = (from p in conexao.Posts where p.bVisivel select p);

//  Verificando se é nulo a tag
            if (!string.IsNullOrEmpty(tag))
            {
                //  Any acha o primiero valor, 
                posts = (from p in posts where p.PostTags.Any(x => x.sIdTag.ToUpper() == tag.ToUpper()) select p);
            }

//  Verifica quando não é nulo e nem vazio a pesquisa
            if (!string.IsNullOrEmpty(pesquisa))
            {
                posts = (from p in posts where p.sTitulo.ToUpper().Contains(pesquisa.ToUpper())
                        ||  p.sResumo.ToUpper().Contains(pesquisa.ToUpper())
                        ||  p.sDescricao.ToUpper().Contains(pesquisa.ToUpper())
                         select p);
            }

            var qtdeRegistros = posts.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdeRegistrosPular = (indiceDaPagina * registroPorPagina);
            //  Arendonta para cima
            var qtdePaginas = Math.Ceiling((decimal)qtdeRegistros / (decimal)registroPorPagina);

            var viewModel = new ListarPostsViewModel();
            viewModel.Posts = (from p in posts orderby p.dDataPublicacao descending select new DetalhesPostViewModel
            {
                DataPublicacao = p.dDataPublicacao,
                Autor = p.sAutor,
                Descricao = p.sDescricao,
                id = p.Id,
                Resumo = p.sResumo,
                Titulo = p.sTitulo,
                Visivel = p.bVisivel,
                QtdComentarios = p.Comentarios.Count
            }
            ).Skip(qtdeRegistrosPular).Take(registroPorPagina).ToList();


            viewModel.iPaginaAtual = paginaCorreta;
            viewModel.iTotalDePaginas = (int)qtdePaginas;
            viewModel.sTag = tag;

            viewModel.sTags = (from p in conexao.Tags where conexao.TagPosts.Any(x => x.sIdTag == p.sIDTag) orderby p.sIDTag ascending select p.sIDTag).ToList();

            viewModel.sPesquisa = pesquisa;
            return View(viewModel);
        }

        public ActionResult _Paginacao()
        {
            return PartialView();
        }

        #region
        public ActionResult Post(int id, int? pagina)
        {
            var conexao = new ConexaoBanco();
            var viewModel = new DetalhesPostViewModel();
            var post = (from p in conexao.Posts where p.Id == id select p).FirstOrDefault();

            if (post == null)
            {
                throw new Exception(string.Format("Post Código {0} não encontrado"));
            }
            preencherViewModel(viewModel, post, pagina);


            viewModel.Tags = (from p in post.PostTags select p.sIdTag).ToList();

            return View(viewModel);
        }

        private static void preencherViewModel(DetalhesPostViewModel viewModel, Post post, int? pagina)
        {
            viewModel.id = post.Id;
            viewModel.Titulo = post.sTitulo;
            viewModel.Autor = post.sAutor;
            viewModel.DataPublicacao = post.dDataPublicacao;
            viewModel.HoraPublicacao = post.dDataPublicacao;
            viewModel.Visivel = post.bVisivel;
            viewModel.Descricao = post.sDescricao;
            viewModel.Resumo = post.sResumo;
            viewModel.QtdComentarios = post.Comentarios.Count();
            viewModel.Descricao = post.sDescricao;
            //Adicionar tags
            viewModel.Tags = post.PostTags.Select(x => x.sIdTag).ToList();
            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registroPorPagina = 10;
            var qtdeRegistros = post.Comentarios.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdeRegistrosPular = (indiceDaPagina * registroPorPagina);
            //  Arendonta para cima
            var qtdePaginas = Math.Ceiling((decimal)qtdeRegistros / (decimal)registroPorPagina);

            viewModel.iLComentarios = (from p in post.Comentarios orderby p.dDataHora descending select p)
            .Skip(qtdeRegistrosPular).Take(registroPorPagina).ToList();

            viewModel.iPaginaAtual = paginaCorreta;
            viewModel.iTotalPaginas = (int)qtdePaginas;
        }
        #endregion

        #region
        [HttpPost]
        public ActionResult Post(DetalhesPostViewModel viewModel)
        {
            var conexao = new ConexaoBanco();
            var post = (from p in conexao.Posts where p.Id == viewModel.id select p).FirstOrDefault();

            if (ModelState.IsValid)
            {

                if (post == null)
                {
                    throw new Exception(string.Format("Post código {0} não encontrado.", viewModel.id));
                }
                var comentario = new Comentario();
                comentario.bAdmPost = HttpContext.User.Identity.IsAuthenticated;
                comentario.lDescricao = viewModel.ComentarioDescricao;
                comentario.sEmail = viewModel.ComentarioEmail;
                comentario.idPost = viewModel.id;
                comentario.sNome = viewModel.ComentarioNome;
                comentario.sPaginaWeb = viewModel.ComentarioPaginaWeb;
                comentario.dDataHora = DateTime.Now;

                try
                {
                    conexao.Comentarios.Add(comentario);
                    conexao.SaveChanges();
                    return Redirect(Url.Action("Post", new
                    {
                        ano = post.dDataPublicacao.Year,
                        mes = post.dDataPublicacao.Month,
                        dia = post.dDataPublicacao.Day,
                        titulo = post.sTitulo,
                        id = post.Id
                    }) + "#comentarios");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                }
            }
            preencherViewModel(viewModel, post, null);
            return View(viewModel);
        }
        #endregion

        public ActionResult _PaginacaoPost()
        {
            return PartialView();
        }
    }
}

BlogFelipeWeb/Controllers/ContUsuario/ContUsuarioController.cs
using BlogFelipe.DB;
using BlogFelipeWeb.Models.Administracao;
using System;
using System.Web.Mvc;

using BlogFelipe.DB.Classes;
using System.Linq;

namespace BlogFelipeWeb.Controllers.ContUsuario
{
    [Authorize]
    public class ContUsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CadastrarUsuario()
        {
            var viewModel = new CadastrarUsuarioViewModel();

            return View(viewModel);
        }
        
        [HttpPost]
        public ActionResult CadastrarUsuario(CadastrarUsuarioViewModel viewModel)
        {
            if (ModelState.IsValid) {
                var conexao = new ConexaoBanco();
                var usuario = new Usuario();

                usuario.sLogin = viewModel.sLogin;
                usuario.sNome = viewModel.sNome;
                usuario.sSenha = viewModel.sSenha;

                var acho = conexao.Usuarios.Where(x => x.sNome == usuario.sNome).FirstOrDefault();

                if (acho == null)
                 {
                    try
                    {
                        conexao.Usuarios.Add(usuario);
                        conexao.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception exp)
                    {
                        ModelState.AddModelError("Erro Banco:", exp.Message);
                    }
                }
                else
                {
                    throw new Exception(string.Format("Usuario já Cadastrado"));
                }
            }
            return View(viewModel);
        }

        public ActionResult EditarUsuario(int id)
        {
            var viewModel = new CadastrarUsuarioViewModel();
            var conexao = new ConexaoBanco();
            var usuario = conexao.Usuarios.Where(x => x.Id == id).FirstOrDefault();

            if (usuario == null)
            {
                throw new Exception(string.Format("Posto com código {0} não encontrado.", id));
            }
            viewModel.iId = usuario.Id;
            viewModel.sLogin = usuario.sLogin;
            viewModel.sNome = usuario.sNome;
            viewModel.sSenha = usuario.sSenha;
            
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditarUsuario(CadastrarUsuarioViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new ConexaoBanco();
                var usuarios = conexao.Usuarios.Where(x => x.Id == viewModel.iId).FirstOrDefault();

                usuarios.Id = viewModel.iId;
                usuarios.sLogin = viewModel.sLogin;
                usuarios.sNome = viewModel.sNome;
                usuarios.sSenha = viewModel.sSenha;

                //var acho = conexao.Usuarios.Where(x => x.sNome == viewModel.sNome && x.Id == viewModel.iId).FirstOrDefault();
                var acho = (from p in conexao.Usuarios where p.Id != viewModel.iId && p.sNome == viewModel.sNome  select p).FirstOrDefault();

                if (acho == null)
                {
                    try
                    {
                        //conexao.Usuarios.Add(usuarios);
                        conexao.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception exp)
                    {
                        ModelState.AddModelError("Erro Banco:", exp.Message);
                    }                    
                }
                else
                {
                    throw new Exception(string.Format("Usuario já cadastrado!"));
                }
            }
            return View(viewModel);
        }

        #region
        public ActionResult ExcluirUsuario(int id)
        {
            var conexao = new ConexaoBanco();
            var usuario = (from p in conexao.Usuarios where p.Id == id select p).FirstOrDefault();

            if (usuario == null)
            {
                throw new Exception(string.Format("Post código {0} não exite.", id));
            }
            conexao.Usuarios.Remove(usuario);
            conexao.SaveChanges();

            return RedirectToAction("Index", "Administracao");
        }
        #endregion
    }
}

BlogFelipeWeb/Controllers/ContUsuario/ListaUsuariosController.cs
using BlogFelipe.DB;
using BlogFelipeWeb.Models.ContUsuario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFelipeWeb.Controllers.ContUsuario
{
    public class ListaUsuariosController : Controller
    {
        // GET: ListaUsuarios
        public ActionResult Index(int? pagina)
        {
            var conexao = new ConexaoBanco();

            var paginaCorreta = pagina.GetValueOrDefault(1);
            var registroPorPagina = 10;
            var usuarios = (from p in conexao.Usuarios orderby p.Id select p);

            var qtdRegistros = usuarios.Count();
            var indiceDaPagina = paginaCorreta - 1;
            var qtdRegistroPular = (indiceDaPagina * registroPorPagina);

            var qtdPaginas = Math.Ceiling((decimal)qtdRegistros / (decimal)registroPorPagina);

            var viewModel = new ListarUsuariosViewModel();            
            viewModel.Usuarios = usuarios.Skip(qtdRegistroPular).Take(registroPorPagina).ToList();
            viewModel.iPaginaAtual = paginaCorreta;
            viewModel.iTotalDePaginas = (int)qtdPaginas;
            return View(viewModel);
        }

        public ActionResult _Paginacao()
        {
            return PartialView();
        }
    }
}

BlogFelipeWeb/Views/Administracao/CadastrarPost.cshtml
@model BlogFelipeWeb.Models.Administracao.CadastrarPostViewModel
@{
    ViewBag.Title = "CadastrarPost";
}

@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Administracao/CadastrarPost.js")"></script>
}


@using (@Html.BeginForm())
{ 
<h2>Cadastrar Post</h2>
@Html.ValidationSummary(true)


<div class="form-group">
    @Html.LabelFor(x => x.Titulo)
    @Html.TextBoxFor(x => x.Titulo, new {@class = "form-control"})
    @Html.ValidationMessageFor(x => x.Titulo)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Autor)
    @Html.TextBoxFor(x => x.Autor, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Autor)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.DataPublicacao)
    @Html.ValidationMessageFor(x => x.DataPublicacao)
    @Html.TextBoxFor(x => x.DataPublicacao, "{0:yyyy-MM-dd}",    
    new { type = "date", @class = "form-control", style = "width=200px" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.HoraPublicacao)
    @Html.ValidationMessageFor(x => x.HoraPublicacao)
    @Html.TextBoxFor(x => x.HoraPublicacao, "{0:HH:mm}",
    new { type = "time", @class = "form-control", style = "width=200px" })
</div>

<div class="checkbox">
    @Html.LabelFor(x => x.Visivel)
    @Html.CheckBoxFor(x => x.Visivel)
    @Html.ValidationMessageFor(x => x.Visivel)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Descricao)
    @Html.ValidationMessageFor(x => x.Descricao)
    @Html.TextAreaFor(x => x.Descricao, new { rows = 8, @class = "form-control" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Resumo)
    @Html.ValidationMessageFor(x => x.Resumo)
    @Html.TextAreaFor(x => x.Resumo, new { rows = 8, @class = "form-control" })
</div>

<h2> Tags </h2>

<div class="form-group cadastro-post">
    @Html.Label("Tag")
    @Html.TextBox("Tag","", new { @class="form-control"})

    <p>
        <input type="button" value="Adicionar" id="adicionar" class="btn btn-primary">
    </p>
</div>

<div class="form-group">
    <ul id="resultado">
        @if (Model.Tags != null)
        {
            foreach (var item in Model.Tags)
            {
                <li><span> @item</span><a tag="@item" class="remover-tag icone-excluir" title="Remover"></a></li>
                <input type="hidden" name="Tags" value="@item" />
            }
        }
    </ul>
</div>
    <p>
        <input type="submit" value="Salvar" class="btn btn-primary">
    </p>

    }

BlogFelipeWeb/Views/Administracao/EditarPost.cshtml
@model BlogFelipeWeb.Models.Administracao.CadastrarPostViewModel
@{
    ViewBag.Title = "EditarPost";
}

@section Scripts
{
    <script src="@Url.Content("~/Scripts/Views/Administracao/CadastrarPost.js")"></script>
}

@using (@Html.BeginForm())
{ 
<h2>Cadastrar Post</h2>
@Html.ValidationSummary(true)

    <div class="form-group">
        @Html.LabelFor(x => x.id)
        @Html.TextBoxFor(x => x.id, new { @class = "form-control" , @disabled = "disable" })
        @Html.ValidationMessageFor(x => x.id)
        @Html.HiddenFor(x => x.id)
    </div>


<div class="form-group">
    @Html.LabelFor(x => x.Titulo)
    @Html.TextBoxFor(x => x.Titulo, new {@class = "form-control"})
    @Html.ValidationMessageFor(x => x.Titulo)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Autor)
    @Html.TextBoxFor(x => x.Autor, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Autor)
</div>
<div class="form-group">
    @Html.LabelFor(x => x.DataPublicacao)
    @Html.ValidationMessageFor(x => x.DataPublicacao)
    @Html.TextBoxFor(x => x.DataPublicacao, "{0:yyyy-MM-dd}",    
    new { type = "date", @class = "form-control", style = "width=200px" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.HoraPublicacao)
    @Html.ValidationMessageFor(x => x.HoraPublicacao)
    @Html.TextBoxFor(x => x.HoraPublicacao, "{0:HH:mm}",
    new { type = "time", @class = "form-control", style = "width=200px" })
</div>

<div class="checkbox">
    @Html.LabelFor(x => x.Visivel)
    @Html.CheckBoxFor(x => x.Visivel)
    @Html.ValidationMessageFor(x => x.Visivel)
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Descricao)
    @Html.ValidationMessageFor(x => x.Descricao)
    @Html.TextAreaFor(x => x.Descricao, new { rows = 8, @class = "form-control" })
</div>

<div class="form-group">
    @Html.LabelFor(x => x.Resumo)
    @Html.ValidationMessageFor(x => x.Resumo)
    @Html.TextAreaFor(x => x.Resumo, new { rows = 8, @class = "form-control" })
</div>

<h2> Tags </h2>

<div class="form-group cadastro-post">
    @Html.Label("Tag")
    @Html.TextBox("Tag", "", new { @class = "form-control" })

    <p>
        <input type="button" value="Adicionar" id="adicionar" class="btn btn-primary">
    </p>
</div>

<div class="form-group">
    <ul id="resultado">
        @if (Model.Tags != null)
        {
            foreach (var item in Model.Tags)
            {
                <li><span> @item</span><a tag="@item" class="remover-tag icone-excluir" title="Remover"></a></li>
                <input type="hidden" name="Tags" value="@item" />
            }
        }
    </ul>
</div>

<p>
    <input type="submit" value="Salvar" class="btn btn-primary" >
</p>

}

BlogFelipeWeb/Views/Administracao/index.cshtml
@{
    ViewBag.Title = "Administração";
}

<h2>Administração</h2>

@Html.ActionLink("Novo Post", "CadastrarPost")

<p>@Html.ActionLink("Listar Post", "Index", "Blog")</p>

<h2>Usuario</h2>

@Html.ActionLink("Novo Usuario", "CadastrarUsuario", "ContUsuario")

<p>@Html.ActionLink("Listar Usuario", "Index", "ListaUsuarios")</p>