BlogFelipeWeb/Controllers/ContUsuario/ContUsuarioController.cs
using BlogFelipe.DB;
using BlogFelipeWeb.Models.Administracao;
using System;
using System.Web.Mvc;

using BlogFelipe.DB.Classes;
using System.Linq;

namespace BlogFelipeWeb.Controllers.ContUsuario
{
    [Authorize]
    public class ContUsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CadastrarUsuario()
        {
            var viewModel = new CadastrarUsuarioViewModel();

            return View(viewModel);
        }
        
        [HttpPost]
        public ActionResult CadastrarUsuario(CadastrarUsuarioViewModel viewModel)
        {
            if (ModelState.IsValid) {
                var conexao = new ConexaoBanco();
                var usuario = new Usuario();

                usuario.sLogin = viewModel.sLogin;
                usuario.sNome = viewModel.sNome;
                usuario.sSenha = viewModel.sSenha;

                var acho = conexao.Usuarios.Where(x => x.sNome == usuario.sNome).FirstOrDefault();

                if (acho == null)
                 {
                    try
                    {
                        conexao.Usuarios.Add(usuario);
                        conexao.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception exp)
                    {
                        ModelState.AddModelError("Erro Banco:", exp.Message);
                    }
                }
                else
                {
                    throw new Exception(string.Format("Usuario já Cadastrado"));
                }
            }
            return View(viewModel);
        }

        public ActionResult EditarUsuario(int id)
        {
            var viewModel = new CadastrarUsuarioViewModel();
            var conexao = new ConexaoBanco();
            var usuario = conexao.Usuarios.Where(x => x.Id == id).FirstOrDefault();

            if (usuario == null)
            {
                throw new Exception(string.Format("Posto com código {0} não encontrado.", id));
            }
            viewModel.iId = usuario.Id;
            viewModel.sLogin = usuario.sLogin;
            viewModel.sNome = usuario.sNome;
            viewModel.sSenha = usuario.sSenha;
            
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditarUsuario(CadastrarUsuarioViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var conexao = new ConexaoBanco();
                var usuarios = conexao.Usuarios.Where(x => x.Id == viewModel.iId).FirstOrDefault();

                usuarios.Id = viewModel.iId;
                usuarios.sLogin = viewModel.sLogin;
                usuarios.sNome = viewModel.sNome;
                usuarios.sSenha = viewModel.sSenha;

                //var acho = conexao.Usuarios.Where(x => x.sNome == viewModel.sNome && x.Id == viewModel.iId).FirstOrDefault();
                var acho = (from p in conexao.Usuarios where p.Id != viewModel.iId && p.sNome == viewModel.sNome  select p).FirstOrDefault();

                if (acho == null)
                {
                    try
                    {
                        //conexao.Usuarios.Add(usuarios);
                        conexao.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception exp)
                    {
                        ModelState.AddModelError("Erro Banco:", exp.Message);
                    }                    
                }
                else
                {
                    throw new Exception(string.Format("Usuario já cadastrado!"));
                }
            }
            return View(viewModel);
        }

        #region
        public ActionResult ExcluirUsuario(int id)
        {
            var conexao = new ConexaoBanco();
            var usuario = (from p in conexao.Usuarios where p.Id == id select p).FirstOrDefault();

            if (usuario == null)
            {
                throw new Exception(string.Format("Post código {0} não exite.", id));
            }
            conexao.Usuarios.Remove(usuario);
            conexao.SaveChanges();

            return RedirectToAction("Index", "Administracao");
        }
        #endregion
    }
}

BlogFelipeWeb/Controllers/Login/LoginController.cs
using BlogFelipe.DB;
using BlogFelipeWeb.Models.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BlogFelipeWeb.Controllers.Login
{
    //Comando para bloquar o acesso a usuarios nao habilitados
    [Authorize]
    public class LoginController : Controller
    {
        // GET: Login
        #region Index
        //  Para ter usuarios sem login
        [AllowAnonymous]
        public ActionResult Index(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }
        
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginViewModel viewModel, string ReturnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var conexao = new ConexaoBanco();
            var usuario = (from p in conexao.Usuarios
                           where p.sLogin.ToUpper() == viewModel.sLogin.ToUpper() &&
                           p.sSenha == viewModel.sSenha
                           select p).FirstOrDefault();
            if (usuario == null)
            {
                ModelState.AddModelError("","Usuário e/ou senha estão incorretos.");
                return View(viewModel);
            }

            FormsAuthentication.SetAuthCookie(viewModel.sLogin, viewModel.Lembrar);

            if (ReturnUrl != null)
            {
                return Redirect(ReturnUrl);
            }
            return RedirectToAction("Index", "Blog");
        }
        #endregion

        #region Sair
        public ActionResult Sair()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }
        #endregion
    }
}

BlogFelipeWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Blog do Felipe</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blog do Felipe", "Index", "Blog", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Administração", "Index", "Administracao")</li>
                        <li>@Html.ActionLink("Usuários", "Index", "ContUsuario")</li>
                        <li>@Html.ActionLink("Sair", "Sair","Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login","Index", "Login")</li>
                    }
                    
                </ul>
                <form method="get" action="~/Blog/Index" class="navbar-form navbar-right">
                    <div>
                        @Html.TextBox("Pesquisa", null, new { placeholder = "Pesquisar", @class = "form-control"})
                    </div>       
                </form>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Blog do Felipe</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>